name:                theHarmonicAlgorithm
version:             0.1.0
license:             BSD3
author:              "HarmAlgo Team"
maintainer:          ""

dependencies:
  - base >= 4.14 && < 5
  - text
  - bytestring
  - containers
  - vector
  - mtl
  - stm
  - cassava
  - data-default
  - statistics
  - split
  - hasbolt
  - tidal
  - hosc
  - tidal-core
  - tidal-link
  - connection
  - tls
  # Phase C: Interactive Behaviour
  - aeson           # JSON parsing for r.weights from Neo4j
  - random          # Base randomness for weighted selection
  - mwc-random      # High-quality gamma distribution sampling

library:
  exposed-modules:
    - Harmonic.Lib
    - Harmonic.Config
    # Framework (R→E→T Orchestration)
    - Harmonic.Framework.Builder
    # Rules (R Component + Layer A)
    - Harmonic.Rules.Types.Pitch
    - Harmonic.Rules.Types.Harmony
    - Harmonic.Rules.Types.Progression
    - Harmonic.Rules.Constraints.Filter
    - Harmonic.Rules.Constraints.Overtone
    - Harmonic.Rules.Import.CSV
    - Harmonic.Rules.Import.Types
    - Harmonic.Rules.Import.Transform
    - Harmonic.Rules.Import.Graph
    # Evaluation (E Component + Layer C)
    - Harmonic.Evaluation.Scoring.Dissonance
    - Harmonic.Evaluation.Scoring.VoiceLeading
    - Harmonic.Evaluation.Database.Query
    - Harmonic.Evaluation.Analysis.Markov
    # Traversal (T Component + Layer C)
    - Harmonic.Traversal.Probabilistic
    # Interface (Layer D)
    - Harmonic.Interface.Tidal.Bridge
    - Harmonic.Interface.Tidal.Arranger
    - Harmonic.Interface.Tidal.Instruments
    - Harmonic.Interface.Tidal.Utils
  source-dirs: src
  # ghc-options:
    # - -Wall

executables:
  theHarmonicAlgorithm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - theHarmonicAlgorithm
      - text
      - cassava
      - statistics
      - hasbolt
      - containers
tests:
  theHarmonicAlgorithm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - theHarmonicAlgorithm
      - hspec
      - QuickCheck
      - containers
      - text
      - tidal