-- |
-- Module      : Harmonic.Framework.BuilderPSpec
-- Description : Tests for the genP (strata-first) paradigm

module Harmonic.Framework.BuilderPSpec (spec) where

import Test.Hspec
import qualified Data.Sequence as Seq
import Data.Foldable (toList)
import Data.List (nub, sort)
import qualified Data.Set as Set

import qualified Harmonic.Rules.Types.Pitch as P
import qualified Harmonic.Rules.Types.Scale as Sc
import qualified Harmonic.Rules.Types.ProgressionContext as PC
import qualified Harmonic.Rules.Types.Progression as Prog
import qualified Harmonic.Rules.Types.Harmony as H
import           Harmonic.Rules.Types.Harmony
  ( initCadenceState, stateCadence, cadenceIntervals, stateCadenceRoot )
import           Harmonic.Framework.Builder
  ( cue, len, seek, tonal, relStrata, absStrata
  , sameBoost, flipBoost, triBoost
  , attempt, entropy
  , genP, genVI, genI, genI', genI''
  , gen, gen', gen''
  , genFrom, genFrom', genFrom''
  , hContext, hcTristrata
  , GenConfig(..), defaultGenConfig, GenMode(..), Verbosity(..)
  )
import qualified Harmonic.Framework.Builder.Strata as Strata
import qualified Harmonic.Evaluation.Scoring.Progression as PS
import           Control.Monad (replicateM)
import qualified Data.List
import           System.IO (IOMode(..), stdout, hFlush, openFile, hClose)
import qualified GHC.IO.Handle
import           Control.Exception (bracket, bracket_)
import           Data.IORef (IORef, newIORef, atomicModifyIORef')
import           System.IO.Unsafe (unsafePerformIO)

{-# NOINLINE captureCounter #-}
captureCounter :: IORef Int
captureCounter = unsafePerformIO (newIORef 0)

-- |Redirect stdout to a unique temp file, run the action, restore stdout,
-- and return the captured bytes. Unique filenames per call avoid macOS
-- "resource busy (file is locked)" errors when several captures run back-
-- to-back inside one hspec process.
captureStdout :: IO () -> IO String
captureStdout act = do
  n <- atomicModifyIORef' captureCounter (\x -> (x + 1, x + 1))
  let tmpPath = "/tmp/hspec_capture_" ++ show n ++ ".txt"
  hFlush stdout
  bracket
    (GHC.IO.Handle.hDuplicate stdout)
    (\saved -> do
       GHC.IO.Handle.hDuplicateTo saved stdout
       hClose saved)
    (\_saved ->
       bracket (openFile tmpPath WriteMode) hClose $ \h ->
         bracket_
           (GHC.IO.Handle.hDuplicateTo h stdout)
           (hFlush stdout)
           act)
  readFile tmpPath

-- |Count occurrences of the chord-grid header marker in captured output.
-- One occurrence corresponds to one printed progression block.
gridHeaderCount :: String -> Int
gridHeaderCount = length . filter isHeaderLine . lines
  where
    isHeaderLine ln =
      "generated by 'The Harmonic Algorithm'" `Data.List.isInfixOf` ln
        || "harmonic traversal" `Data.List.isInfixOf` ln

-- |Helper: extract the (Tristrata, StrataLabel) provenance list.
provList :: PC.ProgressionContext -> [(Sc.Tristrata, Sc.StrataLabel)]
provList pc = maybe [] toList (PC.pcProvenance pc)

-- |Per-bar triad PC set from the triad layer (absolute PCs: root + intervals).
triadAbsolutePCs :: PC.ProgressionContext -> [[Int]]
triadAbsolutePCs pc =
  let states = toList (Prog.unProgression (PC.triadLayer pc))
  in map absPCs states
  where
    absPCs cs =
      let rootPC = P.unPitchClass (P.pitchClass (stateCadenceRoot cs))
          ints   = map P.unPitchClass (cadenceIntervals (stateCadence cs))
      in [(i + rootPC) `mod` 12 | i <- ints]

-- |Pick a known-valid cue for a strata — uses the 3 lowest PCs of the
-- strata's chroma (zero-formed from the lowest as root). Guarantees
-- cue-containment for that strata, so tests don't trigger the
-- invalid-cue abort.
validCueFor :: Sc.StrataLabel -> H.CadenceState
validCueFor s =
  let pcs   = sort (map P.unPitchClass (Sc.strataChroma s))
      top3  = take 3 pcs
      root  = head top3
      ivals = [ (p - root) `mod` 12 | p <- top3 ]
      rname = show (H.enharmonicFunc (H.defaultEnharm (P.mkPitchClass root))
                                      (P.mkPitchClass root))
  in initCadenceState 0 rname ivals

spec :: Spec
spec = describe "genP paradigm" $ do

  -- Strata-I-valid cue used across most tests. genVI tests use a VI-valid
  -- cue separately where needed.
  let start = validCueFor Sc.VI

  describe "basic invariants" $ do
    it "genP VI produces the requested length" $ do
      pc <- seek "none" $ cue start $ len 6 $ genVI
      PC.pcLength pc `shouldBe` 6
      length (provList pc) `shouldBe` 6

    it "all three layers have equal length" $ do
      pc <- seek "none" $ cue start $ len 8 $ genVI
      let tL = Prog.progLength (PC.triadLayer pc)
          sL = Prog.progLength (PC.strataLayer pc)
          mL = Prog.progLength (PC.modeLayer pc)
      tL `shouldBe` 8
      sL `shouldBe` 8
      mL `shouldBe` 8

    it "carries 3-5-7 pitch-set cardinality (triad/strata/mode)" $ do
      pc <- seek "none" $ cue start $ len 8 $ genVI
      let layerCardinalities prog =
            map (length . cadenceIntervals . stateCadence)
                (toList (Prog.unProgression prog))
      layerCardinalities (PC.triadLayer pc)  `shouldBe` replicate 8 3
      layerCardinalities (PC.strataLayer pc) `shouldBe` replicate 8 5
      layerCardinalities (PC.modeLayer pc)   `shouldBe` replicate 8 7

    it "strata-layer chroma matches strataChroma rooted on triad's harmonic root" $ do
      pc <- seek "none" $ cue start $ len 6 $ genVI
      let triadRoots = [ P.unPitchClass (P.pitchClass (H.chordNoteName (H.fromCadenceState cs)))
                       | cs <- toList (Prog.unProgression (PC.triadLayer pc)) ]
          strataAbs  = [ sort [ (i + r) `mod` 12
                              | i <- map P.unPitchClass
                                       (cadenceIntervals (stateCadence cs)) ]
                       | (cs, r) <- zip (toList (Prog.unProgression (PC.strataLayer pc))) triadRoots ]
          expected   = [ sort (map P.unPitchClass (Sc.strataChroma s))
                       | (_, s) <- provList pc ]
      strataAbs `shouldBe` expected

    it "populates pcProvenance (Just)" $ do
      pc <- seek "none" $ cue start $ len 4 $ genVI
      case PC.pcProvenance pc of
        Just _  -> pure ()
        Nothing -> expectationFailure "expected Just provenance"

  describe "initial placement (bar 0)" $ do
    it "seeds strata = VI and tristrata = index 2 (lowest-dissonance containing VI)" $ do
      pc <- seek "none" $ cue start $ len 1 $ genVI
      case provList pc of
        ((t, s) : _) -> do
          s `shouldBe` Sc.VI
          t `shouldBe` Sc.tristrataIndex 2
        _ -> expectationFailure "empty provenance"

    it "genI seeds strata = I and tristrata = index 1" $ do
      pc <- seek "none" $ cue (validCueFor Sc.I) $ len 1 $ genI
      case provList pc of
        ((t, s) : _) -> do
          s `shouldBe` Sc.I
          t `shouldBe` Sc.tristrataIndex 1
        _ -> expectationFailure "empty provenance"

  describe "single-strata containment invariant" $ do
    it "every triad's absolute PCs ⊆ the current strata's chroma" $ do
      pc <- seek "none" $ cue start $ len 8 $ genVI
      let bars  = triadAbsolutePCs pc
          prov  = provList pc
      length bars `shouldBe` length prov
      -- The triad layer is generated by R→E→T with _hcOvertones narrowed to
      -- the strata's chroma, so every triad's absolute PCs must be a subset
      -- of the strata's chroma PCs.
      let strataPCs s = Set.fromList (map P.unPitchClass (Sc.strataChroma s))
      sequence_
        [ Set.fromList tri `shouldSatisfy` (`Set.isSubsetOf` strataPCs s)
        | (tri, (_, s)) <- zip bars prov
        ]

  describe "hcTristrata lock" $ do
    it "hcTristrata \"5\" restricts every bar's tristrata to index 5" $ do
      let ctx = hcTristrata "5" hContext
      pc <- seek "none" $ cue start $ tonal ctx $ len 6 $ genP Sc.VI
      let t5 = Sc.tristrataIndex 5
      sequence_ [ t `shouldBe` t5 | (t, _) <- provList pc ]

    it "hcTristrata \"5\" forces strata drawn only from {IV, VI, X}" $ do
      let ctx = hcTristrata "5" hContext
      pc <- seek "none" $ cue start $ tonal ctx $ len 6 $ genP Sc.VI
      let allowedStrata = Set.fromList [Sc.IV, Sc.VI, Sc.X]
      sequence_
        [ s `shouldSatisfy` (`Set.member` allowedStrata)
        | (_, s) <- provList pc
        ]

    it "hcTristrata whitelist \"1 2\" never yields other tristratas" $ do
      let ctx = hcTristrata "1 2" hContext
      pc <- seek "none" $ cue (validCueFor Sc.V) $ tonal ctx $ len 8 $ genP Sc.V
      let allowed = Set.fromList [Sc.tristrataIndex 1, Sc.tristrataIndex 2]
      sequence_ [ t `shouldSatisfy` (`Set.member` allowed) | (t, _) <- provList pc ]

  describe "relStrata / absStrata modifiers" $ do
    it "relStrata \"1 2 3\" sets length to 3 when len not given" $ do
      pc <- seek "none" $ cue start $ relStrata "1 2 3" $ genVI
      PC.pcLength pc `shouldBe` 3

    it "absStrata \"I V X\" sets length to 3 and forces the strata sequence" $ do
      pc <- seek "none" $ cue (validCueFor Sc.I) $ absStrata "I V X" $ genI
      PC.pcLength pc `shouldBe` 3
      -- Bar 0 is fixed to the starting strata (I); bars 1..2 narrow to the
      -- requested labels.
      let ss = [s | (_, s) <- provList pc]
      take 1 ss `shouldBe` [Sc.I]

    it "len called after relStrata overrides the length" $ do
      pc <- seek "none" $ cue start $ len 4 $ relStrata "1 2 3" $ genVI
      -- relStrata sets len=3; then len 4 wipes the override.
      -- Modifier chain is applied outside-in, so `len 4` is applied AFTER
      -- relStrata, which is the behaviour we want.
      PC.pcLength pc `shouldBe` 4

  describe "alias equivalence" $ do
    it "genVI and genP VI both seed strata VI at bar 0" $ do
      -- Each run is stochastic from bar 1 onward (the walk samples
      -- candidates uniformly excluding self-loops), so provenance lists
      -- aren't equal in general. Bar 0 is deterministic via
      -- 'initialPlacement' and must be strata VI for both aliases.
      pcA <- seek "none" $ cue start $ len 4 $ genVI
      pcB <- seek "none" $ cue start $ len 4 $ genP Sc.VI
      case (provList pcA, provList pcB) of
        ((_, sA) : _, (_, sB) : _) -> do
          sA `shouldBe` Sc.VI
          sB `shouldBe` Sc.VI
        _ -> expectationFailure "empty provenance"

  describe "per-bar diagnostics" $ do
    it "strata chroma has exactly 5 PCs matching strataChroma of the provenance" $ do
      pc <- seek "none" $ cue start $ len 4 $ genVI
      let prov = provList pc
      -- Every provenance strata has a 5-PC chroma.
      sequence_
        [ length (Sc.strataChroma s) `shouldBe` 5 | (_, s) <- prov ]

    it "mode classification yields a 7-PC chroma" $ do
      -- For the first provenance entry, modeFor produces a Mode whose
      -- chroma is 7 PCs (28-mode taxonomy classification).
      pc <- seek "none" $ cue start $ len 4 $ genVI
      case provList pc of
        []        -> expectationFailure "empty provenance"
        ((t,s):_) ->
          length (Sc.modeChroma (Sc.Mode Sc.Aeolian (P.mkPitchClass 0))) `shouldBe` 7
          -- (Generic check that modeChroma returns 7 PCs;
          -- bar-level modeFor requires the R→E→T diagnostic collection,
          -- covered end-to-end in the REPL smoke test.)

  describe "R→E→T integration" $ do
    it "triad bars are not all identical (composer-statistical, not deterministic)" $ do
      -- With the MVP's deterministic 'representative' helper every bar
      -- picked the same 3-PC slice; under R→E→T with gamma the triads
      -- must vary across a 12-bar run.
      pc <- seek "none" $ cue start $ len 12 $ genVI
      let bars = triadAbsolutePCs pc
      -- At least two distinct triads must appear across 12 bars.
      length (nub bars) `shouldSatisfy` (>= 2)

    it "boost = 1.0 disables continuity bias without breaking generation" $ do
      pc <- seek "none" $ cue start $ sameBoost 1.0 $ flipBoost 1.0 $ triBoost 1.0 $ len 8 $ genVI
      PC.pcLength pc `shouldBe` 8
      -- Containment still holds with unit boosts (narrowing does the work).
      let bars = triadAbsolutePCs pc
          prov = provList pc
          strataPCs s = Set.fromList (map P.unPitchClass (Sc.strataChroma s))
      sequence_
        [ Set.fromList tri `shouldSatisfy` (`Set.isSubsetOf` strataPCs s)
        | (tri, (_, s)) <- zip bars prov
        ]

    it "containment preserved under strong same-strata boost" $ do
      pc <- seek "none" $ cue start $ sameBoost 0.1 $ len 10 $ genVI
      let bars = triadAbsolutePCs pc
          prov = provList pc
          strataPCs s = Set.fromList (map P.unPitchClass (Sc.strataChroma s))
      sequence_
        [ Set.fromList tri `shouldSatisfy` (`Set.isSubsetOf` strataPCs s)
        | (tri, (_, s)) <- zip bars prov
        ]

    it "hcTristrata lock + containment survives R→E→T" $ do
      let ctx = hcTristrata "5" hContext
      pc <- seek "none" $ cue start $ tonal ctx $ len 10 $ genP Sc.VI
      let t5 = Sc.tristrataIndex 5
          bars = triadAbsolutePCs pc
          prov = provList pc
          strataPCs s = Set.fromList (map P.unPitchClass (Sc.strataChroma s))
      sequence_ [ t `shouldBe` t5 | (t, _) <- prov ]
      sequence_
        [ Set.fromList tri `shouldSatisfy` (`Set.isSubsetOf` strataPCs s)
        | (tri, (_, s)) <- zip bars prov
        ]

    it "strict containment (no bass exemption) holds for every bar" $ do
      -- Every bar's triad (including its bass note) must lie in the
      -- bar's own active strata — even when the walk traverses to a
      -- different strata mid-run. Uses the per-bar provenance.
      pc <- seek "none" $ cue start $ len 16 $ genP Sc.II
      let bars = triadAbsolutePCs pc
          prov = provList pc
          strataPCs s = Set.fromList (map P.unPitchClass (Sc.strataChroma s))
      length bars `shouldBe` length prov
      sequence_
        [ Set.fromList tri `shouldSatisfy` (`Set.isSubsetOf` strataPCs s)
        | (tri, (_, s)) <- zip bars prov
        ]

  describe "mode-invariant" $ do
    -- The Aeolian fallback in 'modeOf' was removed. The modeLayer now stores
    -- the actual 'ModeResult' chroma — 7 PCs for 'ModeOk', 6 PCs for
    -- 'ModeInvalid' (only reachable if a bar sequence violates 'allowedNext'
    -- adjacency). 'narrow' applies 'absStrata'/'relStrata' AFTER 'allowedNext',
    -- so walk-driven generation cannot violate adjacency and therefore cannot
    -- produce 'ModeInvalid'. These tests lock that invariant.

    it "modeForTriad returns ModeInvalid for an adjacency-violating barSeq" $ do
      -- Hand-craft a barSeq the walk could never produce: bar 0 = VII in T9
      -- (V,VII,IX), bar 1 = X in T1 (I,V,X). X is NOT in any tristrata
      -- containing VII, so this is not a valid 'allowedNext' transition.
      -- 'pickPartner' at bar 1 returns VII; VII+X pair-union is 6-PC.
      let badSeq = [ (Sc.VII, Sc.tristrataIndex 9)
                   , (Sc.X,   Sc.tristrataIndex 1)
                   ]
      case Strata.modeForTriad badSeq 1 0 of
        Sc.ModeInvalid pcs -> length pcs `shouldBe` 6
        Sc.ModeOk _        -> expectationFailure "expected ModeInvalid for VII+X cross-tristrata pair"

    it "natural walks always yield 7-PC mode layers (genVI)" $ do
      pc <- seek "none" $ cue start $ len 16 $ genVI
      let cardinalities = map (length . cadenceIntervals . stateCadence)
                              (toList (Prog.unProgression (PC.modeLayer pc)))
      cardinalities `shouldBe` replicate 16 7

    it "natural walks always yield 7-PC mode layers (genI)" $ do
      pc <- seek "none" $ cue (validCueFor Sc.I) $ len 16 $ genI
      let cardinalities = map (length . cadenceIntervals . stateCadence)
                              (toList (Prog.unProgression (PC.modeLayer pc)))
      cardinalities `shouldBe` replicate 16 7

    it "absStrata-driven walks also yield 7-PC mode layers (narrow runs after allowedNext)" $ do
      -- absStrata can only restrict within already-valid adjacencies; it
      -- can't force a non-allowedNext transition. Pool-empty cases self-loop
      -- to prev, preserving adjacency.
      pc <- seek "none" $ cue (validCueFor Sc.I) $ absStrata "I V X" $ genI
      let cardinalities = map (length . cadenceIntervals . stateCadence)
                              (toList (Prog.unProgression (PC.modeLayer pc)))
      all (== 7) cardinalities `shouldBe` True

    it "relStrata-driven walks also yield 7-PC mode layers" $ do
      pc <- seek "none" $ cue start $ relStrata "1 2 3 1 2 3" $ genVI
      let cardinalities = map (length . cadenceIntervals . stateCadence)
                              (toList (Prog.unProgression (PC.modeLayer pc)))
      all (== 7) cardinalities `shouldBe` True

    it "hcTristrata + override walks still yield 7-PC mode layers" $ do
      let ctx = hcTristrata "5" hContext
      pc <- seek "none" $ cue start $ tonal ctx $ relStrata "1 2 3" $ genP Sc.VI
      let cardinalities = map (length . cadenceIntervals . stateCadence)
                              (toList (Prog.unProgression (PC.modeLayer pc)))
      all (== 7) cardinalities `shouldBe` True

  describe "attempt modifier (multi-attempt rank-and-select)" $ do
    it "defaults to single-pass behaviour when not invoked" $ do
      _gcMaxAttempts defaultGenConfig `shouldBe` 1
      _gcViableTarget defaultGenConfig `shouldBe` 1

    it "sets fields with the given (viableTarget, maxAttempts)" $ do
      let gc = attempt 3 12 defaultGenConfig
      _gcViableTarget gc `shouldBe` 3
      _gcMaxAttempts gc  `shouldBe` 12

    it "clamps zero / negative inputs to 1" $ do
      let gc = attempt 0 (-5) defaultGenConfig
      _gcViableTarget gc `shouldBe` 1
      _gcMaxAttempts gc  `shouldBe` 1

    it "strata-aware genFrom keeps untouched bars intact" $ do
      let cueE = H.initCadenceState 0 "E" [0,3,7]
      s <- seek "none" $ len 6 $ cue cueE $ entropy 0.4 $ genVI
      s' <- seek "none" $ entropy 0.4 $ genFrom s 3 4
      let triadsOf pc = map H.stateCadenceRoot
                            (toList (Prog.unProgression (PC.triadLayer pc)))
          before = triadsOf s
          after  = triadsOf s'
      -- Bars 1, 2, 5, 6 (0-indexed: 0, 1, 4, 5) must be unchanged.
      [before !! i | i <- [0, 1, 4, 5]] `shouldBe` [after !! i | i <- [0, 1, 4, 5]]
      length after `shouldBe` 6

    it "strata-aware genFrom preserves Just provenance with matching length" $ do
      let cueE = H.initCadenceState 0 "E" [0,3,7]
      s <- seek "none" $ len 6 $ cue cueE $ entropy 0.4 $ genVI
      s' <- seek "none" $ entropy 0.4 $ genFrom s 3 4
      case PC.pcProvenance s' of
        Just sq -> length (toList sq) `shouldBe` 6
        Nothing -> expectationFailure "expected Just provenance"

    it "strata-aware genFrom keeps every bar's modeLayer at 7 PCs (Phase 1 invariant across splice)" $ do
      let cueE = H.initCadenceState 0 "E" [0,3,7]
      s <- seek "none" $ len 8 $ cue cueE $ entropy 0.4 $ genI
      s' <- seek "none" $ entropy 0.4 $ genFrom s 3 5
      let cards = map (length . cadenceIntervals . stateCadence)
                      (toList (Prog.unProgression (PC.modeLayer s')))
      cards `shouldBe` replicate 8 7

    it "genFrom dispatches to FromProgPC when source has provenance" $ do
      let cueE = H.initCadenceState 0 "E" [0,3,7]
      s <- seek "none" $ len 4 $ cue cueE $ entropy 0.4 $ genVI
      let gc = genFrom s 2 3
      case _gcMode gc of
        FromProgPC _ a b -> do { a `shouldBe` 2; b `shouldBe` 3 }
        _                -> expectationFailure "expected FromProgPC mode for genP-derived context"

    it "genFrom' sets Standard verbosity and preserves the FromProgPC range" $ do
      let cueE = H.initCadenceState 0 "E" [0,3,7]
      s <- seek "none" $ len 4 $ cue cueE $ entropy 0.4 $ genVI
      let gc = genFrom' s 2 3
      _gcVerbosity gc `shouldBe` Standard
      case _gcMode gc of
        FromProgPC _ a b -> do { a `shouldBe` 2; b `shouldBe` 3 }
        _                -> expectationFailure "expected FromProgPC mode for genFrom' on genP-derived context"

    it "genFrom'' sets Verbose verbosity and preserves the FromProgPC range" $ do
      let cueE = H.initCadenceState 0 "E" [0,3,7]
      s <- seek "none" $ len 4 $ cue cueE $ entropy 0.4 $ genVI
      let gc = genFrom'' s 2 3
      _gcVerbosity gc `shouldBe` Verbose
      case _gcMode gc of
        FromProgPC _ a b -> do { a `shouldBe` 2; b `shouldBe` 3 }
        _                -> expectationFailure "expected FromProgPC mode for genFrom'' on genP-derived context"

    describe "Verbose (gen'') scoreboard rendering (Phase 10)" $ do
      it "Verbose + attempt 3 12 prints the Multi-attempt scoreboard with ← PICK" $ do
        let cueC = H.initCadenceState 0 "C" [0,4,7]
        out <- captureStdout $ do
          _ <- seek "none" $ len 4 $ cue cueC $ entropy 0.5 $ attempt 3 12 $ gen''
          pure ()
        out `shouldSatisfy` ("Multi-attempt" `Data.List.isInfixOf`)
        out `shouldSatisfy` ("← PICK"        `Data.List.isInfixOf`)
        out `shouldSatisfy` ("picked: #"     `Data.List.isInfixOf`)

      it "Silent + attempt 3 12 does NOT print the scoreboard" $ do
        let cueC = H.initCadenceState 0 "C" [0,4,7]
        out <- captureStdout $ do
          _ <- seek "none" $ len 4 $ cue cueC $ entropy 0.5 $ attempt 3 12 $ gen
          pure ()
        out `shouldNotSatisfy` ("Multi-attempt" `Data.List.isInfixOf`)
        out `shouldNotSatisfy` ("← PICK"        `Data.List.isInfixOf`)

      it "Standard + attempt 3 12 does NOT print the scoreboard" $ do
        let cueC = H.initCadenceState 0 "C" [0,4,7]
        out <- captureStdout $ do
          _ <- seek "none" $ len 4 $ cue cueC $ entropy 0.5 $ attempt 3 12 $ gen'
          pure ()
        out `shouldNotSatisfy` ("Multi-attempt" `Data.List.isInfixOf`)

      it "Verbose + attempt 1 1 (default, no multi-attempt) does NOT print the scoreboard" $ do
        let cueC = H.initCadenceState 0 "C" [0,4,7]
        out <- captureStdout $ do
          _ <- seek "none" $ len 4 $ cue cueC $ entropy 0.5 $ gen''
          pure ()
        out `shouldNotSatisfy` ("Multi-attempt" `Data.List.isInfixOf`)

      it "Scoreboard contains exactly one ← PICK marker" $ do
        let cueC = H.initCadenceState 0 "C" [0,4,7]
        out <- captureStdout $ do
          _ <- seek "none" $ len 4 $ cue cueC $ entropy 0.5 $ attempt 3 12 $ gen''
          pure ()
        let pickCount = length (filter ("← PICK" `Data.List.isInfixOf`) (lines out))
        pickCount `shouldBe` 1

    describe "Single-winner grid in multi-attempt mode (Phase 11)" $ do
      it "gen + attempt 3 6 prints exactly one chord-grid block" $ do
        let cueE = H.initCadenceState 0 "E" [0,3,7]
        out <- captureStdout $ do
          _ <- seek "none" $ len 6 $ cue cueE $ entropy 0.3 $ attempt 3 6 $ gen
          pure ()
        gridHeaderCount out `shouldBe` 1

      it "gen' + attempt 3 6 prints exactly one chord-grid block plus Standard trace" $ do
        let cueE = H.initCadenceState 0 "E" [0,3,7]
        out <- captureStdout $ do
          _ <- seek "none" $ len 6 $ cue cueE $ entropy 0.3 $ attempt 3 6 $ gen'
          pure ()
        gridHeaderCount out `shouldBe` 1
        out `shouldSatisfy` ("Generation:" `Data.List.isInfixOf`)

      it "gen'' + attempt 3 6 prints exactly one chord-grid block plus Verbose trace plus scoreboard" $ do
        let cueE = H.initCadenceState 0 "E" [0,3,7]
        out <- captureStdout $ do
          _ <- seek "none" $ len 6 $ cue cueE $ entropy 0.3 $ attempt 3 6 $ gen''
          pure ()
        gridHeaderCount out `shouldBe` 1
        out `shouldSatisfy` ("Verbose Generation:" `Data.List.isInfixOf`)
        out `shouldSatisfy` ("Multi-attempt"       `Data.List.isInfixOf`)
        out `shouldSatisfy` ("← PICK"              `Data.List.isInfixOf`)

      it "single-pass gen prints exactly one chord-grid block (regression)" $ do
        let cueE = H.initCadenceState 0 "E" [0,3,7]
        out <- captureStdout $ do
          _ <- seek "none" $ len 6 $ cue cueE $ entropy 0.3 $ gen
          pure ()
        gridHeaderCount out `shouldBe` 1

      it "strata-genFrom single-pass prints the full spliced grid (not regen segment)" $ do
        let cueE = H.initCadenceState 0 "E" [0,3,7]
        s <- seek "none" $ len 6 $ cue cueE $ entropy 0.3 $ genI
        let sLen = Prog.progLength (PC.triadLayer s)
        sLen `shouldBe` 6
        out <- captureStdout $ do
          r <- seek "none" $ entropy 0.4 $ genFrom s 3 4
          let rLen = Prog.progLength (PC.triadLayer r)
          rLen `shouldBe` sLen
        gridHeaderCount out `shouldBe` 1

      it "strata-genFrom + attempt 3 6 prints exactly one full-progression grid" $ do
        let cueE = H.initCadenceState 0 "E" [0,3,7]
        s <- seek "none" $ len 6 $ cue cueE $ entropy 0.3 $ genI
        out <- captureStdout $ do
          r <- seek "none" $ attempt 3 6 $ entropy 0.4 $ genFrom s 3 4
          let rLen = Prog.progLength (PC.triadLayer r)
          rLen `shouldBe` Prog.progLength (PC.triadLayer s)
        gridHeaderCount out `shouldBe` 1

    describe "Winner-trace + composing line (Phase 12)" $ do
      it "gen' + attempt 3 6 (strata) shows all bars in the Strata walk, not just the starter" $ do
        let cueE = H.initCadenceState 0 "E" [0,3,7]
        out <- captureStdout $ do
          _ <- seek "none" $ len 4 $ cue cueE $ entropy 0.3 $ attempt 3 6 $ genI'
          pure ()
        -- Each generated bar's per-step trace contributes one "strata "
        -- line. Pre-Phase-12 this would be 1 (starter only).
        let strataLines = length (filter ("    strata " `Data.List.isInfixOf`) (lines out))
        strataLines `shouldBe` 4

      it "gen'' + attempt 3 6 (strata) shows the Verbose-only soft-boost lines for the winner" $ do
        let cueE = H.initCadenceState 0 "E" [0,3,7]
        out <- captureStdout $ do
          _ <- seek "none" $ len 4 $ cue cueE $ entropy 0.3 $ attempt 3 6 $ genI''
          pure ()
        -- "boost" lines are emitted only by 'renderStrataStep' at
        -- verbosity 2, so their presence proves the K-attempt loop
        -- collected at Verbose, not Standard.
        out `shouldSatisfy` ("    boost " `Data.List.isInfixOf`)

      it "multi-attempt invocations open with the 'composing ..' line" $ do
        let cueE = H.initCadenceState 0 "E" [0,3,7]
        out <- captureStdout $ do
          _ <- seek "none" $ len 4 $ cue cueE $ entropy 0.3 $ attempt 3 6 $ gen
          pure ()
        out `shouldSatisfy` ("composing .." `Data.List.isInfixOf`)

      it "single-pass invocations do NOT print the 'composing ..' line" $ do
        let cueE = H.initCadenceState 0 "E" [0,3,7]
        out <- captureStdout $ do
          _ <- seek "none" $ len 4 $ cue cueE $ entropy 0.3 $ gen
          pure ()
        out `shouldNotSatisfy` ("composing .." `Data.List.isInfixOf`)

    it "attempt 3 12 picks progressions whose mean score beats the baseline mean" $ do
      -- Baseline: 30 single-pass attempts.
      let cueE = H.initCadenceState 0 "E" [0,3,7]
      baseline <- replicateM 30 (seek "none" $ len 8 $ cue cueE $ genVI)
      let baselineScores =
            map (PS.totalScore PS.defaultWeightsOffline . PS.scoreProgression) baseline
          meanBaseline = sum baselineScores / fromIntegral (length baselineScores)

      -- 8 multi-attempt picks.
      picks <- replicateM 8 (seek "none" $ len 8 $ cue cueE $ attempt 3 12 $ genVI)
      let pickScores =
            map (PS.totalScore PS.defaultWeightsOffline . PS.scoreProgression) picks
          meanPicks = sum pickScores / fromIntegral (length pickScores)

      -- 'best of 12' should pull the mean toward the upper tail.
      meanPicks `shouldSatisfy` (> meanBaseline)
