{-# LANGUAGE OverloadedStrings #-}

-- |
-- Module      : Harmonic.Framework.Builder.Diagnostics
-- Description : Diagnostic printing and chord tracing for generation
--
-- Functions for printing generation diagnostics at various verbosity levels,
-- computing chord traces during generation, and rendering chord names.

module Harmonic.Framework.Builder.Diagnostics
  ( -- * Diagnostic Printing
    printDiagnostics
  , printHeader
  , printStrataDiagnostics

    -- * Chord Tracing
  , computeChordTrace
  , showChord

    -- * Candidate Rendering
  , parseCadenceFromString
  ) where

import           Control.Monad (forM_, when)
import           Data.List (sort)
import qualified Data.Text as T
import           Data.Text (Text)

import qualified Harmonic.Rules.Types.Harmony as H
import qualified Harmonic.Rules.Types.Pitch as P
import qualified Harmonic.Rules.Types.Progression as Prog
import qualified Harmonic.Rules.Types.Scale as Sc

import           Harmonic.Framework.Builder.Types
import           Harmonic.Framework.Builder.Portmanteau (makePortmanteau)

-------------------------------------------------------------------------------
-- Header Printing
-------------------------------------------------------------------------------

-- | Print generation header based on composer selection
-- Takes raw Text instead of parsed ComposerWeights, plus entropy
printHeader :: Text -> Double -> HarmonicContext -> IO ()
printHeader composerStr entropy ctx = do
  if T.toLower composerStr == "none"
    then putStrLn "|= offline =| harmonic traversal (fallback only — no graph) -> https://github.com/OscarSouth/theHarmonicAlgorithm"
    else case makePortmanteau composerStr of
      Just portmanteau ->
        putStrLn $ "|= \"" ++ T.unpack portmanteau
                ++ "\" =| harmonic traversal -> https://github.com/OscarSouth/theHarmonicAlgorithm"
      Nothing ->
        putStrLn "generated by 'The Harmonic Algorithm' -> https://github.com/OscarSouth/theHarmonicAlgorithm"
  putStrLn $ "   entropy " ++ show entropy ++ " | " ++ show ctx

-------------------------------------------------------------------------------
-- Diagnostic Printing
-------------------------------------------------------------------------------

-- |Print diagnostics collected during generation.
--
-- Selects output level based on verbosity parameter:
--
-- [0 - Silent] No output
-- [1 - Standard] Per-step candidate pools, selections, rendered chords
-- [2 - Verbose] Standard plus transform and advance traces
--
-- Useful for manually reprinting diagnostics after extraction from tuple,
-- or batch processing multiple results at different verbosity levels.
printDiagnostics :: Int -> GenerationDiagnostics -> IO ()
printDiagnostics 0 _ = pure ()  -- No output for verbosity 0
printDiagnostics verbosity diag = do
  -- Header with context
  putStrLn ""
  putStrLn "═══════════════════════════════════════════════════════════════════"
  putStrLn "GENERATION DIAGNOSTICS"
  putStrLn "═══════════════════════════════════════════════════════════════════"
  putStrLn $ "Start: " ++ gdStartCadence diag ++ " @ " ++ gdStartRoot diag
  putStrLn $ "Length: " ++ show (gdActualLen diag) ++ "/" ++ show (gdRequestedLen diag) ++ " chords"
  putStrLn $ "Entropy: " ++ show (gdEntropy diag)
  putStrLn ""

  -- Per-step diagnostics
  let steps = gdSteps diag
  forM_ steps $ \step -> do
    let stepNum = sdStepNumber step
    putStrLn $ "──── STEP " ++ show stepNum ++ " ────"
    putStrLn $ "  Prior: " ++ sdPriorCadence step ++ " @ " ++ sdPriorRoot step

    -- Candidate pool summary
    let graphCount = sdGraphCount step
        fallbackCount = sdFallbackCount step
        poolSize = sdPoolSize step
    putStrLn $ "  Pool: graph=" ++ show graphCount ++ " fallback=" ++ show fallbackCount ++ " total=" ++ show poolSize

    -- Top candidates (if available)
    when (graphCount > 0) $
      putStrLn $ "    Graph top 3: " ++ show (take 3 $ sdGraphTop6 step)

    when (fallbackCount > 0) $
      putStrLn $ "    Fallback top 3: " ++ show (take 3 [(n, s) | (n, s, _, _, _) <- sdFallbackTop6 step])

    -- Selection details
    putStrLn $ "  Selection: " ++ sdSelectedFrom step ++ " @ gamma index " ++ show (sdGammaIndex step)
    putStrLn $ "  Movement: " ++ sdSelectedDbMovement step
    putStrLn $ "  Posterior: " ++ sdPosteriorRoot step

    -- Rendered chord (verbosity 1+)
    case sdRenderedChord step of
      Just chord -> putStrLn $ "  Chord: " ++ chord
      Nothing -> return ()

    -- Transform trace (verbosity 2+)
    when (verbosity >= 2) $ case sdTransformTrace step of
      Just tt -> do
        putStrLn "  [TRANSFORM TRACE]"
        putStrLn $ "    DB tones: " ++ show (ttTones tt)
        putStrLn $ "    Transposed (root+tones): " ++ show (ttTransposedPitches tt)
        putStrLn $ "    Normalized: " ++ show (ttNormalizedPs tt)
        putStrLn $ "    Zero-form: " ++ show (ttZeroForm tt)
        putStrLn $ "    Detected root: " ++ ttDetectedRoot tt
        putStrLn $ "    Computed name: " ++ ttFunctionality tt
        putStrLn $ "    DB stored name: " ++ ttStoredFunc tt
      Nothing -> return ()

    -- Advance trace (verbosity 2+)
    when (verbosity >= 2) $ case sdAdvanceTrace step of
      Just at -> do
        putStrLn "  [ADVANCE TRACE]"
        putStrLn $ "    Root motion: " ++ atCurrentRoot at ++ " " ++ show (atCurrentRootPC at)
                   ++ " + " ++ show (atMovementInterval at) ++ " → " ++ show (atNewRootPC at)
        putStrLn $ "    Spelling: " ++ atNewRoot at
      Nothing -> return ()

    putStrLn ""

  -- Final progression
  putStrLn "═══════════════════════════════════════════════════════════════════"
  putStrLn "FINAL PROGRESSION:"
  putStrLn "═══════════════════════════════════════════════════════════════════"
  print (gdProgression diag)
  putStrLn ""

-------------------------------------------------------------------------------
-- Chord Tracing
-------------------------------------------------------------------------------

-- |Compute chord rendering and transform trace based on verbosity level.
-- Note: Reads raw DB data from the cadence within the state (which is the selected cadence after advance).
computeChordTrace :: Int -> H.CadenceState -> (Maybe String, Maybe TransformTrace)
computeChordTrace verbosity state
  | verbosity >= 2 =
      let (chord, ttt) = H.fromCadenceStateTraced state

          tt = TransformTrace
            { ttRawDbIntervals = H.tttRawDbIntervals ttt
            , ttRawDbMovement = H.tttRawDbMovement ttt
            , ttRawDbFunctionality = H.tttRawDbFunctionality ttt
            , ttRootPC = H.tttRootPC ttt
            , ttRootNoteName = H.tttRootNoteName ttt
            , ttTones = H.tttTones ttt
            , ttTransposedPitches = H.tttTransposedPitches ttt
            , ttNormalizedPs = H.tttNormalizedPs ttt
            , ttZeroForm = H.tttZeroForm ttt
            , ttDetectedRoot = H.tttDetectedRoot ttt
            , ttFunctionality = H.tttFunctionality ttt
            , ttFinalChord = H.tttFinalChord ttt
            , ttStoredFunc = H.tttStoredFunc ttt
            }
      in (Just $ showChord chord, Just tt)
  | verbosity >= 1 =
      let chord = H.fromCadenceState state
      in (Just $ showChord chord, Nothing)
  | otherwise = (Nothing, Nothing)

-- |Show a chord as "Root Functionality"
showChord :: H.Chord -> String
showChord c = show (H.chordNoteName c) ++ " " ++ H.chordFunctionality c

-------------------------------------------------------------------------------
-- Candidate Rendering
-------------------------------------------------------------------------------

-- | Parse candidate name like "( pedal -> min )" and render with posterior root
-- Returns "C min" for "( pedal -> min )" when posterior root is C
parseCadenceFromString :: String -> Int -> Maybe String
parseCadenceFromString name posteriorRootPC =
  let -- Strip parentheses: "( pedal -> min )" → " pedal -> min "
      cleaned = filter (\c -> c /= '(' && c /= ')') name
      -- Find arrow position and split
      (before, after) = break (== '>') (dropWhile (/= '-') cleaned)
  in if null after || null before
     then Nothing
     else let functionality = trim (tail after)  -- skip '>'
              posteriorRoot = show (P.sharp (P.mkPitchClass posteriorRootPC))
          in Just $ posteriorRoot ++ " " ++ functionality
  where
    trim :: String -> String
    trim = dropWhile (== ' ') . reverse . dropWhile (== ' ') . reverse

-------------------------------------------------------------------------------
-- Strata Diagnostics (genP paradigm)
-------------------------------------------------------------------------------

-- |Per-bar rendering for 'genP'/'genP\''/'genP\'\''. Shows the triad
-- (3 notes), the strata chroma (5 notes), the mode chroma (7 notes), the
-- active tristrata, and — at verbosity 2 — the soft-boost applied.
--
-- Noop when 'sdStrataLabel' is 'Nothing' for every step, so it's safe to
-- call unconditionally on any diagnostics value.
printStrataDiagnostics :: Int -> GenerationDiagnostics -> IO ()
printStrataDiagnostics verbosity diag = do
  let steps = gdSteps diag
      hasStrata = any (\s -> sdStrataLabel s /= Nothing) steps
  if not hasStrata
    then pure ()
    else do
      putStrLn ""
      putStrLn $ "Strata walk: " ++ gdStartRoot diag
                 ++ " → " ++ show (gdActualLen diag) ++ " bars (entropy "
                 ++ show (gdEntropy diag) ++ ")"
      putStrLn "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      forM_ steps $ \step -> renderStrataStep verbosity step
      putStrLn "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      putStrLn ""

-- |Per-bar renderer. Layout is a three-line block (header + strata +
-- mode) sharing a common indent (4 spaces) and four column widths:
-- label, identifier, info, chroma.
--
-- @
--     <barNum>:      <motion>         <chord>             [<src>] γ=<idx>
--     strata         <Roman>          #<idx> (<ts1>-<ts2>-<ts3>)  {<n1> <n2> ...}
--     mode           <Root Quality>   (<Parent Family>)           {<n1> <n2> ...}
-- @
--
-- For 'ModeInvalid' (only via 'absStrata' overrides that violate
-- tristrata adjacency), the mode line reads
-- @mode           invalid overlap                                 {<overlap PCs>}@.
renderStrataStep :: Int -> StepDiagnostic -> IO ()
renderStrataStep verbosity step = do
  let isStarter = sdSelectedFrom step == "starter"
      chord  = case sdRenderedChord step of
                 Just c  -> c
                 Nothing -> sdPosteriorRoot step
      motion
        | isStarter = "— → " ++ sdPosteriorRoot step
        | otherwise = sdPriorRoot step ++ " → " ++ sdPosteriorRoot step
      pivotPC = case sdHarmonicRootPC step of
                  Just pc -> pc
                  Nothing -> sdPosteriorRootPC step
      -- Per-bar spelling, inferred by 'runStrataGen' via 'H.inferSpelling'
      -- on the mode chroma. Falls back to 'defaultEnharm' when missing
      -- (non-genP callers).
      spelling = case sdBarSpelling step of
        Just s  -> s
        Nothing -> H.defaultEnharm (P.mkPitchClass pivotPC)
      enharm = H.enharmonicFunc spelling
      src
        | isStarter = "[starter]"
        | otherwise = "[" ++ sdSelectedFrom step ++ "] γ=" ++ show (sdGammaIndex step)

  -- Header row: aligned on the same four columns as strata/mode.
  putStrLn $ indent
             ++ pad labelWidth (show (sdStepNumber step) ++ ":")
             ++ pad identWidth motion
             ++ pad infoWidth chord
             ++ src

  -- Strata row — Roman label in ident column, tristrata tag in info
  -- column (merged), chroma in the final column.
  case (sdStrataLabel step, sdStrataChroma step) of
    (Just sl, Just chroma) ->
      let tagStr = case (sdTristrataIdx step, sdTristrata step) of
            (Just idx, Just t) ->
              "#" ++ show idx
                  ++ " (" ++ show (Sc.ts1 t)
                  ++ "-" ++ show (Sc.ts2 t)
                  ++ "-" ++ show (Sc.ts3 t) ++ ")"
            _ -> ""
      in putStrLn $ indent
                    ++ pad labelWidth "strata"
                    ++ pad identWidth (show sl)
                    ++ pad infoWidth tagStr
                    ++ showPCNamesCurly enharm pivotPC chroma
    _ -> pure ()

  -- Mode row — handle ModeOk vs ModeInvalid.
  case sdModeResult step of
    Just (Sc.ModeInvalid overlap) ->
      putStrLn $ indent
                 ++ pad labelWidth "mode"
                 ++ pad identWidth "invalid overlap"
                 ++ pad infoWidth ""
                 ++ showPCNamesCurly enharm 0 overlap
    _ ->
      case (sdMode step, sdModeChroma step) of
        (Just m, Just chroma) ->
          let modeRootPC  = P.unPitchClass (Sc.modeRoot m)
              parentTag   = case sdParentKey step of
                Just (P.P pr, fam) ->
                  "(" ++ show (enharm (P.mkPitchClass pr))
                      ++ " " ++ Sc.showScaleFamily fam ++ ")"
                Nothing -> ""
          in putStrLn $ indent
                        ++ pad labelWidth "mode"
                        ++ pad identWidth (modeLabelWith enharm m)
                        ++ pad infoWidth parentTag
                        ++ showPCNamesCurly enharm modeRootPC chroma
        _ -> pure ()

  when (verbosity >= 2) $
    case sdSoftBoost step of
      Just b  -> putStrLn $ indent ++ pad labelWidth "boost" ++ show b
      Nothing -> pure ()

  putStrLn ""
  where
    indent       = "    "
    labelWidth   = 11   -- covers "tristrata", "strata", "mode", "N:"
    identWidth   = 16   -- covers "F# Mixolydian" (13), tolerant to 16
    infoWidth    = 22   -- covers "#10 (IV-VI-XI)" (14) and "(F# Harmonic Major)" (19)

-- |Render a PC list inside curly brackets, ordered from the given pivot PC
-- up. The pivot is used to rotate the sorted list so the pivot (if
-- present) is first; otherwise sorted order is used. Note names are
-- spelled using the supplied enharmonic function (parent-key driven), so
-- "F# Phrygian (D Major)" renders chroma as "{F# G A B C# D E}", not
-- "{Gb Ab Bbb Cb Db Ebb Fb}".
showPCNamesCurly :: (P.PitchClass -> P.NoteName) -> Int -> [P.PitchClass] -> String
showPCNamesCurly enharm pivot pcs =
  let ns           = sort (map P.unPitchClass pcs)
      (before, after) = break (== pivot) ns
      ordered      = after ++ before
      renderPC n   = show (enharm (P.mkPitchClass n))
  in "{" ++ unwords (map renderPC ordered) ++ "}"

-- |Mode label in musician-readable form using a supplied enharmonic
-- function for the root + the legacy 'toMode' mode-quality strings:
-- @"C# Aeolian"@, @"A Mixo_b6"@, @"Db Lyd_Aug_#2"@. Passing
-- @P.sharp@ / @P.flat@ / @H.enharmonicFunc spelling@ selects the root's
-- accidental.
modeLabelWith :: (P.PitchClass -> P.NoteName) -> Sc.Mode -> String
modeLabelWith f (Sc.Mode q (P.P r)) =
  show (f (P.mkPitchClass r)) ++ " " ++ Sc.showModeQuality q

pad :: Int -> String -> String
pad n s = s ++ replicate (max 0 (n - length s)) ' '
