{-# LANGUAGE OverloadedStrings #-}

-- |
-- Module      : Harmonic.Framework.Builder.Diagnostics
-- Description : Diagnostic printing and chord tracing for generation
--
-- Functions for printing generation diagnostics at various verbosity levels,
-- computing chord traces during generation, and rendering chord names.

module Harmonic.Framework.Builder.Diagnostics
  ( -- * Diagnostic Printing
    printDiagnostics
  , printHeader

    -- * Chord Tracing
  , computeChordTrace
  , showChord

    -- * Candidate Rendering
  , parseCadenceFromString
  ) where

import           Control.Monad (forM_, when)
import qualified Data.Text as T
import           Data.Text (Text)

import qualified Harmonic.Rules.Types.Harmony as H
import qualified Harmonic.Rules.Types.Pitch as P

import           Harmonic.Framework.Builder.Types
import           Harmonic.Framework.Builder.Portmanteau (makePortmanteau)

-------------------------------------------------------------------------------
-- Header Printing
-------------------------------------------------------------------------------

-- | Print generation header based on composer selection
-- Takes raw Text instead of parsed ComposerWeights, plus entropy
printHeader :: Text -> Double -> HarmonicContext -> IO ()
printHeader composerStr entropy ctx = do
  case makePortmanteau composerStr of
    Just portmanteau ->
      putStrLn $ "|= \"" ++ T.unpack portmanteau
              ++ "\" =| harmonic traversal -> https://github.com/OscarSouth/theHarmonicAlgorithm"
    Nothing ->
      putStrLn "generated by 'The Harmonic Algorithm' -> https://github.com/OscarSouth/theHarmonicAlgorithm"
  putStrLn $ "   entropy " ++ show entropy ++ " | " ++ show ctx

-------------------------------------------------------------------------------
-- Diagnostic Printing
-------------------------------------------------------------------------------

-- |Print diagnostics collected during generation.
--
-- Selects output level based on verbosity parameter:
--
-- [0 - Silent] No output
-- [1 - Standard] Per-step candidate pools, selections, rendered chords
-- [2 - Verbose] Standard plus transform and advance traces
--
-- Useful for manually reprinting diagnostics after extraction from tuple,
-- or batch processing multiple results at different verbosity levels.
printDiagnostics :: Int -> GenerationDiagnostics -> IO ()
printDiagnostics 0 _ = pure ()  -- No output for verbosity 0
printDiagnostics verbosity diag = do
  -- Header with context
  putStrLn ""
  putStrLn "═══════════════════════════════════════════════════════════════════"
  putStrLn "GENERATION DIAGNOSTICS"
  putStrLn "═══════════════════════════════════════════════════════════════════"
  putStrLn $ "Start: " ++ gdStartCadence diag ++ " @ " ++ gdStartRoot diag
  putStrLn $ "Length: " ++ show (gdActualLen diag) ++ "/" ++ show (gdRequestedLen diag) ++ " chords"
  putStrLn $ "Entropy: " ++ show (gdEntropy diag)
  putStrLn ""

  -- Per-step diagnostics
  let steps = gdSteps diag
  forM_ steps $ \step -> do
    let stepNum = sdStepNumber step
    putStrLn $ "──── STEP " ++ show stepNum ++ " ────"
    putStrLn $ "  Prior: " ++ sdPriorCadence step ++ " @ " ++ sdPriorRoot step

    -- Candidate pool summary
    let graphCount = sdGraphCount step
        fallbackCount = sdFallbackCount step
        poolSize = sdPoolSize step
    putStrLn $ "  Pool: graph=" ++ show graphCount ++ " fallback=" ++ show fallbackCount ++ " total=" ++ show poolSize

    -- Top candidates (if available)
    when (graphCount > 0) $
      putStrLn $ "    Graph top 3: " ++ show (take 3 $ sdGraphTop6 step)

    when (fallbackCount > 0) $
      putStrLn $ "    Fallback top 3: " ++ show (take 3 [(n, s) | (n, s, _, _, _) <- sdFallbackTop6 step])

    -- Selection details
    putStrLn $ "  Selection: " ++ sdSelectedFrom step ++ " @ gamma index " ++ show (sdGammaIndex step)
    putStrLn $ "  Movement: " ++ sdSelectedDbMovement step
    putStrLn $ "  Posterior: " ++ sdPosteriorRoot step

    -- Rendered chord (verbosity 1+)
    case sdRenderedChord step of
      Just chord -> putStrLn $ "  Chord: " ++ chord
      Nothing -> return ()

    -- Transform trace (verbosity 2+)
    when (verbosity >= 2) $ case sdTransformTrace step of
      Just tt -> do
        putStrLn "  [TRANSFORM TRACE]"
        putStrLn $ "    DB tones: " ++ show (ttTones tt)
        putStrLn $ "    Transposed (root+tones): " ++ show (ttTransposedPitches tt)
        putStrLn $ "    Normalized: " ++ show (ttNormalizedPs tt)
        putStrLn $ "    Zero-form: " ++ show (ttZeroForm tt)
        putStrLn $ "    Detected root: " ++ ttDetectedRoot tt
        putStrLn $ "    Computed name: " ++ ttFunctionality tt
        putStrLn $ "    DB stored name: " ++ ttStoredFunc tt
      Nothing -> return ()

    -- Advance trace (verbosity 2+)
    when (verbosity >= 2) $ case sdAdvanceTrace step of
      Just at -> do
        putStrLn "  [ADVANCE TRACE]"
        putStrLn $ "    Root motion: " ++ atCurrentRoot at ++ " " ++ show (atCurrentRootPC at)
                   ++ " + " ++ show (atMovementInterval at) ++ " → " ++ show (atNewRootPC at)
        putStrLn $ "    Spelling: " ++ atNewRoot at
      Nothing -> return ()

    putStrLn ""

  -- Final progression
  putStrLn "═══════════════════════════════════════════════════════════════════"
  putStrLn "FINAL PROGRESSION:"
  putStrLn "═══════════════════════════════════════════════════════════════════"
  print (gdProgression diag)
  putStrLn ""

-------------------------------------------------------------------------------
-- Chord Tracing
-------------------------------------------------------------------------------

-- |Compute chord rendering and transform trace based on verbosity level.
-- Note: Reads raw DB data from the cadence within the state (which is the selected cadence after advance).
computeChordTrace :: Int -> H.CadenceState -> (Maybe String, Maybe TransformTrace)
computeChordTrace verbosity state
  | verbosity >= 2 =
      let (chord, ttt) = H.fromCadenceStateTraced state

          tt = TransformTrace
            { ttRawDbIntervals = H.tttRawDbIntervals ttt
            , ttRawDbMovement = H.tttRawDbMovement ttt
            , ttRawDbFunctionality = H.tttRawDbFunctionality ttt
            , ttRootPC = H.tttRootPC ttt
            , ttRootNoteName = H.tttRootNoteName ttt
            , ttTones = H.tttTones ttt
            , ttTransposedPitches = H.tttTransposedPitches ttt
            , ttNormalizedPs = H.tttNormalizedPs ttt
            , ttZeroForm = H.tttZeroForm ttt
            , ttDetectedRoot = H.tttDetectedRoot ttt
            , ttFunctionality = H.tttFunctionality ttt
            , ttFinalChord = H.tttFinalChord ttt
            , ttStoredFunc = H.tttStoredFunc ttt
            }
      in (Just $ showChord chord, Just tt)
  | verbosity >= 1 =
      let chord = H.fromCadenceState state
      in (Just $ showChord chord, Nothing)
  | otherwise = (Nothing, Nothing)

-- |Show a chord as "Root Functionality"
showChord :: H.Chord -> String
showChord c = show (H.chordNoteName c) ++ " " ++ H.chordFunctionality c

-------------------------------------------------------------------------------
-- Candidate Rendering
-------------------------------------------------------------------------------

-- | Parse candidate name like "( pedal -> min )" and render with posterior root
-- Returns "C min" for "( pedal -> min )" when posterior root is C
parseCadenceFromString :: String -> Int -> Maybe String
parseCadenceFromString name posteriorRootPC =
  let -- Strip parentheses: "( pedal -> min )" → " pedal -> min "
      cleaned = filter (\c -> c /= '(' && c /= ')') name
      -- Find arrow position and split
      (before, after) = break (== '>') (dropWhile (/= '-') cleaned)
  in if null after || null before
     then Nothing
     else let functionality = trim (tail after)  -- skip '>'
              posteriorRoot = show (P.sharp (P.mkPitchClass posteriorRootPC))
          in Just $ posteriorRoot ++ " " ++ functionality
  where
    trim :: String -> String
    trim = dropWhile (== ' ') . reverse . dropWhile (== ' ') . reverse
