-- |
-- Module      : Harmonic.Framework.Builder.StrataGen
-- Description : The strata-first generator behind 'Harmonic.Framework.Builder.genP'
--
-- Walks a (strata, tristrata) sequence and builds a
-- 'PC.ProgressionContext' with distinct triad\/strata\/mode layers
-- ('runStrataGen'), and regenerates a contiguous range of such a context
-- in place with a walk-valid e→e+1 seam ('runStrataGenFrom'). Pure
-- adjacency rules live in "Harmonic.Framework.Builder.Strata"; this
-- module is the IO runner the facade dispatches to.

module Harmonic.Framework.Builder.StrataGen
  ( runStrataGen
  , runStrataGenFrom
  , printInvalidCueError
  , viableTriadLines
  , mkStarterDiag
  ) where

import qualified Data.Text as T
import           Control.Monad (when)
import           Data.Foldable (toList)
import           Data.List (nub, sort)
import           Data.Maybe (fromMaybe)
import qualified Data.Sequence as Seq
import           System.Random.MWC (GenIO, createSystemRandom, uniformRM)

import qualified Harmonic.Rules.Types.Harmony as H
import qualified Harmonic.Rules.Types.Pitch as P
import qualified Harmonic.Rules.Types.Progression as Prog
import qualified Harmonic.Rules.Types.ProgressionContext as PC
import qualified Harmonic.Rules.Types.Scale as Sc
import           Harmonic.Rules.Constraints.Overtone (possibleTriads)

import           Harmonic.Framework.Builder.Types
import           Harmonic.Framework.Builder.Core
import qualified Harmonic.Framework.Builder.Strata as Strata

-------------------------------------------------------------------------------
-- Strata traversal runner
-------------------------------------------------------------------------------

-- |Walk the (strata, tristrata) sequence for a 'StrataMode' run and build a
-- 'PC.ProgressionContext' with distinct triad\/strata\/mode layers.
--
-- The triad layer is generated by the full R→E→T pipeline: at each bar, the
-- active context's '_hcOvertones' is narrowed to the current strata's 5-PC
-- chroma (prime-notation), 'parseContextOnce' is rerun, and @stepChainBody@
-- is invoked with a 'pcSoftBoost' multiplier computed from strata \/
-- tristrata continuity against prior bars. Graph candidates (Neo4j) and
-- consonance-fallback candidates both flow through the usual filter →
-- score → gamma-select pipeline, with the soft-boost applied to @badness@
-- at @computeFallbackScoreWithBoost@ (fallback) and inversely to
-- confidence in @scoreByConfidence@-output (graph). Single-strata
-- containment is guaranteed by construction: the narrowed overtone set
-- precludes any triad whose chroma escapes @s_i@.
--
-- Strata and mode layer bars are representative 3-PC slices of
-- 'strataChroma s_i' and 'modeChroma m_i' respectively, rooted on the
-- generated triad's root so they transpose with the progression.
runStrataGen :: Sc.StrataLabel -> GenConfig -> IO (PC.ProgressionContext, GenerationDiagnostics)
runStrataGen sStart gc = do
  start <- _gcCue gc
  rng   <- createSystemRandom
  let basePctx = parseContextOnce (_gcTonal gc)
      allowed  = pcAllowedTristrata basePctx
      allowed' = if null allowed then Sc.validTristrata else allowed
      n        = max 1 (fromMaybe (_gcLen gc) (_gcLenOverride gc))
      (s0, t0) = Strata.initialPlacement allowed' sStart

      -- relStrata \/ absStrata narrowing on the walk's candidate pool.
      narrow :: Int -> [(Sc.StrataLabel, Sc.Tristrata)] -> [(Sc.StrataLabel, Sc.Tristrata)]
      narrow i pool =
        let pool1 = case _gcRelStrata gc of
              Just ps | not (null ps) ->
                let p = ps !! (i `mod` length ps)
                in [(s',t') | (s',t') <- pool, Sc.tristrataStrataAt t' p == s']
              _ -> pool
            pool2 = case _gcAbsStrata gc of
              Just ss | not (null ss) ->
                let s = ss !! (i `mod` length ss)
                in [(s',t') | (s',t') <- pool1, s' == s]
              _ -> pool1
        in pool2

  -- Sample one random seed per transition bar. Used by 'selectNextSeeded'
  -- to escape the pathological same-strata fixed point of the purely
  -- categorical 'selectNext'. 'n - 1' seeds cover bars 1..n-1; bar 0 is
  -- set by 'Harmonic.Framework.Builder.Strata.initialPlacement'.
  walkSeeds <- mapM (const (uniformRM (minBound :: Int, maxBound :: Int) rng))
                    [1 .. max 0 (n - 1)]

  let -- Pre-compute the (s_i, t_i) sequence for all n bars using the
      -- seeded stochastic selector (allows genuine traversal rather than
      -- sticking on the starting strata).
      walk :: Int -> [Int] -> (Sc.StrataLabel, Sc.Tristrata) -> [(Sc.StrataLabel, Sc.Tristrata)]
      walk i seeds prev
        | i >= n = []
        | otherwise =
            let cands  = narrow i (Strata.allowedNext allowed' prev)
                (seed, seedsRest) = case seeds of
                  (s : rest) -> (s, rest)
                  []         -> (0, [])
                chosen = fromMaybe prev (Strata.selectNextSeeded seed prev cands)
            in chosen : walk (i + 1) seedsRest chosen

      barSeq :: [(Sc.StrataLabel, Sc.Tristrata)]
      barSeq = (s0, t0) : walk 1 walkSeeds (s0, t0)

      -- Build an overtones string of prime-notation tokens ("C#' D' E'") for
      -- a strata's 5-PC chroma. 'parseOvertones'' treats "X'" as a pinned
      -- single PC (no overtone series expansion), so pcEffectiveOvertones
      -- after parseContextOnce is exactly the 5 PCs of the strata.
      strataOvertonesString :: Sc.StrataLabel -> String
      strataOvertonesString s =
        unwords [ show (P.sharp (P.mkPitchClass (P.unPitchClass pc))) ++ "'"
                | pc <- Sc.strataChroma s ]

      -- Per-bar soft-boost: compare bar i's (s,t) with bar i-1 and i-2.
      -- sameMult  ← candidate matches s_{i-1}      (strata continuity)
      -- flipMult  ← matches s_{i-2} AND not s_{i-1} (flip-flop return)
      -- triMult   ← t_i == t_{i-1}                 (tristrata continuity)
      -- Because the candidate pool is strata-narrowed, every candidate in
      -- bar i has strata s_i; so the (s', t') vs (s_{prev}, t_{prev}) test
      -- collapses to an s_i-vs-s_{prev} scalar. Boost is a per-bar scalar,
      -- applied uniformly across the bar's pool.
      boostFor :: Int -> Double
      boostFor 0 = 1.0  -- bar 0: no prior
      boostFor i =
        let (sCurr, tCurr) = barSeq !! i
            (sPrev, tPrev) = barSeq !! (i - 1)
            sGrand         = if i >= 2 then Just (fst (barSeq !! (i - 2))) else Nothing
            mSame = if sCurr == sPrev then _gcBoostSame gc else 1.0
            mFlip = case sGrand of
                      Just sg | sCurr == sg && sCurr /= sPrev -> _gcBoostFlip gc
                      _                                        -> 1.0
            mTri  = if tCurr == tPrev then _gcBoostTri gc else 1.0
            _     = tPrev  -- keep reference (silence unused warning if any)
        in mSame * mFlip * mTri

      -- Build the per-bar ParsedContext by narrowing _hcOvertones to the
      -- bar's strata chroma and attaching the bar's soft-boost.
      -- The supplier is 1-indexed (bar 1 = first generated bar, which is
      -- barSeq index 1 since barSeq[0] is the starting state).
      pctxAt :: Int -> ParsedContext
      pctxAt barIdx1 =
        let i      = barIdx1  -- barSeq index for the generated bar
            (s, _) = barSeq !! i
            ctx'   = hcOvertones (strataOvertonesString s) (_gcTonal gc)
            pctx   = parseContextOnce ctx'
            boost  = boostFor i
        in pctx { pcSoftBoost = boost
                , pcStrictContainment = True
                }

      -- Cue validation: the starting CadenceState's absolute PCs must all
      -- be members of the starting strata's chroma. If the cue escapes
      -- the strata, abort with a helpful message listing viable triads.
      startAbsPCs =
        let rpc = P.unPitchClass (P.pitchClass (H.stateCadenceRoot start))
            ivs = map P.unPitchClass (H.cadenceIntervals (H.stateCadence start))
        in [ (iv + rpc) `mod` 12 | iv <- ivs ]
      s0PCs      = map P.unPitchClass (Sc.strataChroma s0)
      -- The strata triad layer is triadic by contract (3-5-7): a wider
      -- cue would put a tetrad into an FStrata triad layer, so cue
      -- cardinality is bounded alongside chroma containment.
      cueValid   = length startAbsPCs == 3 && all (`elem` s0PCs) startAbsPCs

  if not cueValid
    then do
      -- Inside a multi-attempt loop every emission is suppressed (the
      -- winner is emitted once); the invalid-cue warning would otherwise
      -- print up to K times. Single-pass keeps the full block.
      when (_gcMaxAttempts gc <= 1) $ do
        when (length startAbsPCs /= 3) $
          putStrLn "genP cues are triadic (the 3-5-7 layer contract) — reduce the cue to three tones inside the stratum:"
        printInvalidCueError start s0
      let emptyPC = PC.ProgressionContext
            { PC.triadLayer   = mempty
            , PC.strataLayer  = mempty
            , PC.modeLayer    = mempty
            , PC.pcProvenance = Just Seq.empty
            , PC.pcFamily     = PC.FStrata
            }
          emptyDiag = GenerationDiagnostics
            { gdStartCadence = show (H.stateCadence start)
            , gdStartRoot    = show (H.stateCadenceRoot start)
            , gdRequestedLen = n
            , gdActualLen    = 0
            , gdEntropy      = _gcEntropy gc
            , gdSteps        = []
            , gdProgression  = mempty
            , gdJazzTrace    = []
            }
      pure (emptyPC, emptyDiag)
    else runStrataGenBody sStart gc start rng s0 t0 barSeq pctxAt boostFor n

-- |Body of 'runStrataGen' after cue validation has passed. Separated so
-- the cue-invalid path can abort cleanly without wiring through the
-- full chain-building machinery.
runStrataGenBody
  :: Sc.StrataLabel
  -> GenConfig
  -> H.CadenceState
  -> GenIO
  -> Sc.StrataLabel
  -> Sc.Tristrata
  -> [(Sc.StrataLabel, Sc.Tristrata)]
  -> (Int -> ParsedContext)
  -> (Int -> Double)
  -> Int
  -> IO (PC.ProgressionContext, GenerationDiagnostics)
runStrataGenBody _sStart gc start rng _s0 _t0 barSeq pctxAt boostFor n = do
  -- Keep the cue as bar 1 (matching 'gen' semantics). Generate n-1 more
  -- bars. Chain has n elements: [cue, gen_1, ..., gen_{n-1}]. Step i of
  -- generation produces chain[i] using barSeq[i]'s strata context.
  let pctxAtStep :: Int -> ParsedContext
      pctxAtStep = pctxAt
      -- Verbosity: Silent → no diagnostics, Standard → Just 1, Verbose → Just 2.
      verbArg = case _gcVerbosity gc of
        Silent   -> Nothing
        Standard -> Just 1
        Verbose  -> Just 2
  source <- sourceFor (T.pack (_gcSeek gc))
  (chain, rawDiags) <- buildChainWith source rng verbArg
                         (_gcEntropy gc) (_gcTonal gc) pctxAtStep start (max 0 (n - 1))

  -- Assemble ProgressionContext. The triadLayer is the R→E→T chain.
  -- Strata & mode layers carry the full chroma (5 PCs \/ 7 PCs respectively)
  -- expressed as intervals from the bar's harmonic root, so they transpose
  -- with the progression and can be voiced as 5- or 7-pitch sets downstream.
  let -- Triad's harmonic root PC (post-detectInversion). For inversions
      -- 'H.stateCadenceRoot' is the bass; we want the harmonic root.
      -- 'H.fromCadenceState' runs detectInversion to set 'chordNoteName'
      -- to the harmonic root.
      harmonicRootOf :: H.CadenceState -> Int
      harmonicRootOf cs =
        P.unPitchClass (P.pitchClass (H.chordNoteName (H.fromCadenceState cs)))

      -- Triad's harmonic root note (used for spelling-aware rootName).
      harmonicRootNote :: H.CadenceState -> P.NoteName
      harmonicRootNote cs = H.chordNoteName (H.fromCadenceState cs)

      -- Express a chroma set as intervals from a chosen root PC. Preserves
      -- full cardinality (no truncation). Always starts at 0 because the
      -- root is in its own chroma by construction (every strata\/mode contains
      -- its own root).
      chromaIntervals :: Int -> [P.PitchClass] -> [Int]
      chromaIntervals rootPC chroma =
        sort $ nub [ (P.unPitchClass p - rootPC) `mod` 12 | p <- chroma ]

      -- Per-bar mode classification, triad-anchored and history-aware.
      modeResults :: [Sc.ModeResult]
      modeResults =
        [ Strata.modeForTriad barSeq i (harmonicRootOf cs)
        | (i, cs) <- zip [0..] chain
        ]

      -- Per-bar chroma stored in the mode layer. 'Harmonic.Rules.Types.Scale.ModeOk' contributes the
      -- 7-PC mode chroma; 'ModeInvalid' contributes its 6-PC overlap PCs
      -- as-is. No Aeolian masquerade — the layer faithfully reflects what
      -- 'modeForTriad' produced. Natural walks always yield 'Harmonic.Rules.Types.Scale.ModeOk' (proven
      -- from 'Harmonic.Framework.Builder.Strata.allowedNext' adjacency); 'ModeInvalid' is reachable only via
      -- explicit 'absStrata' \/ 'relStrata' overrides that violate tristrata
      -- adjacency.
      modeChromaList :: [[P.PitchClass]]
      modeChromaList =
        [ case mr of
            Sc.ModeOk m         -> Sc.modeChroma m
            Sc.ModeInvalid pcs  -> pcs
        | mr <- modeResults
        ]

      -- Build a CadenceState from a root and root-relative intervals,
      -- preserving full cardinality (no initCadenceState\/toCadence
      -- truncation). Delegates to the exported non-truncating constructor;
      -- unlike the historical local version this also populates
      -- cadenceFunctionality, which the display seam (showHarmony) would
      -- otherwise recompute identically.
      mkChromaCS :: P.NoteName -> [Int] -> H.CadenceState
      mkChromaCS root intervals = H.mkCadenceStatePCs root H.Unison intervals

      -- Build per-bar strata-layer + mode-layer CadenceStates rooted on
      -- each generated triad's harmonic root, carrying the full 5 \/ 7 PC
      -- chroma respectively (6 PCs for override-driven 'ModeInvalid' bars).
      mkAuxLayers :: H.CadenceState
                  -> Sc.StrataLabel
                  -> [P.PitchClass]              -- mode/overlap chroma
                  -> (H.CadenceState, H.CadenceState)
      mkAuxLayers triadCS sCurr modeChromaPCs =
        let rootPC     = harmonicRootOf triadCS
            rootNote   = harmonicRootNote triadCS
            strataInts = chromaIntervals rootPC (Sc.strataChroma sCurr)
            modeInts   = chromaIntervals rootPC modeChromaPCs
            strataCS   = mkChromaCS rootNote strataInts
            modeCS     = mkChromaCS rootNote modeInts
        in (strataCS, modeCS)

      stratas = [s | (s, _) <- pairs]
      modes   = [m | (_, m) <- pairs]
      pairs   = zipWith3 mkAuxLayers chain (map fst barSeq) modeChromaList

      provSeq          = Seq.fromList [(t, s) | (s, t) <- take (length chain) barSeq]
      resultPC = PC.ProgressionContext
        { PC.triadLayer   = Prog.fromCadenceStates chain
        , PC.strataLayer  = Prog.fromCadenceStates stratas
        , PC.modeLayer    = Prog.fromCadenceStates modes
        , PC.pcProvenance = Just provSeq
        , PC.pcFamily     = PC.FStrata
        }

  -- Synthesize a "starter" StepDiagnostic for the cue bar (chain[0]) so
  -- the diagnostic loop has one entry per output bar. The cue has no
  -- prior state and wasn't selected from a candidate pool — 'sdSelectedFrom'
  -- = "starter" signals this to the renderer.
  let starterDiag = mkStarterDiag start
      allBaseDiags = starterDiag : rawDiags

  -- Attach strata\/tristrata\/mode\/boost info. allBaseDiags has n entries
  -- aligned with chain \/ barSeq \/ modeList \/ modeResults.
  let tristrataIdxOf t =
        let tpairs = zip Sc.validTristrata [1 :: Int ..]
        in lookup t tpairs
      -- Per-bar enharmonic spelling, derived from the mode's chroma via
      -- 'H.inferSpelling' with the triad's harmonic root as the leading
      -- pitch. Reuses the same tooling as the progression-grid chord
      -- naming (which also threads through 'inferSpelling' inside
      -- 'advanceStateTraced'), but scoped to the bar's full modal context
      -- rather than a single 3-note chord. This gives the diagnostic
      -- block one coherent accidental system.
      barSpellingOf :: [P.PitchClass] -> Int -> H.EnharmonicSpelling
      barSpellingOf chroma rootPC =
        let pcs = rootPC : [p | p <- map P.unPitchClass chroma, p /= rootPC]
        in H.inferSpelling pcs

      -- Slash-notation chord rendering using the bar's spelling.
      slashChordWith :: H.EnharmonicSpelling -> H.CadenceState -> String
      slashChordWith spelling cs =
        Prog.showHarmony (H.enharmonicFunc spelling) cs

      attachedDiags =
        [ let rootPC                = harmonicRootOf cs
              spelling              = barSpellingOf chroma rootPC
              (mMode, mParentKey)   = case mr of
                Sc.ModeOk mode     -> (Just mode, Just (Sc.parentKey mode))
                Sc.ModeInvalid _   -> (Nothing, Nothing)
          in d { sdStepNumber     = i + 1
               , sdRenderedChord  = Just (slashChordWith spelling cs)
               , sdStrataLabel    = Just s
               , sdTristrata      = Just t
               , sdTristrataIdx   = tristrataIdxOf t
               , sdMode           = mMode
               , sdStrataChroma   = Just (Sc.strataChroma s)
               , sdModeChroma     = Just chroma
               , sdSoftBoost      = Just (boostFor i)
               , sdHarmonicRootPC = Just rootPC
               , sdParentKey      = mParentKey
               , sdModeResult     = Just mr
               , sdBarSpelling    = Just spelling
               }
        | (i, d, (s, t), chroma, cs, mr) <- zip6 [0..] allBaseDiags barSeq modeChromaList chain modeResults
        ]
      attachedGen = GenerationDiagnostics
        { gdStartCadence = show (H.stateCadence start)
        , gdStartRoot    = show (H.stateCadenceRoot start)
        , gdRequestedLen = n
        , gdActualLen    = length chain
        , gdEntropy      = _gcEntropy gc
        , gdSteps        = attachedDiags
        , gdProgression  = PC.triadLayer resultPC
        , gdJazzTrace    = []
        }

  -- No inline printing; diagnostics and footer are emitted by the
  -- top-level caller via @emitFinalised@, so that multi-attempt mode
  -- can suppress losing attempts and surface only the winner.
  let _ = verbArg

  pure (resultPC, attachedGen)
  where
    zip6 as bs cs ds es fs =
      [ (a, b, c, d, e, f)
      | ((a, b, c), (d, e, f)) <- zip (zip3 as bs cs) (zip3 ds es fs)
      ]

-- |Build a synthetic starter diagnostic for a 'Harmonic.Framework.Builder.genP' bar 0 (the cue).
-- The cue isn't selected from a candidate pool, so 'sdSelectedFrom' =
-- "starter" signals the renderer to omit the motion\/γ cells.
mkStarterDiag :: H.CadenceState -> StepDiagnostic
mkStarterDiag cs =
  let rootPC = P.unPitchClass (P.pitchClass (H.stateCadenceRoot cs))
  in StepDiagnostic
       { sdStepNumber              = 1
       , sdPriorCadence            = ""
       , sdPriorRoot               = ""
       , sdPriorRootPC             = rootPC
       , sdSelectedDbIntervals     = ""
       , sdSelectedDbMovement      = ""
       , sdSelectedDbFunctionality = ""
       , sdGraphCount              = 0
       , sdGraphTop6               = []
       , sdFallbackCount           = 0
       , sdFallbackTop6            = []
       , sdPoolSize                = 0
       , sdEntropyUsed             = 0
       , sdGammaIndex              = -1
       , sdSelectedFrom            = "starter"
       , sdPosteriorRoot           = show (H.stateCadenceRoot cs)
       , sdPosteriorRootPC         = rootPC
       , sdRenderedChord           = Nothing
       , sdTransformTrace          = Nothing
       , sdAdvanceTrace            = Nothing
       , sdTristrataIdx            = Nothing
       , sdTristrata               = Nothing
       , sdStrataLabel             = Nothing
       , sdMode                    = Nothing
       , sdStrataChroma            = Nothing
       , sdModeChroma              = Nothing
       , sdSoftBoost               = Nothing
       , sdHarmonicRootPC          = Nothing
       , sdParentKey               = Nothing
       , sdModeResult              = Nothing
       , sdBarSpelling             = Nothing
       , sdPoly                    = Nothing
       }

-------------------------------------------------------------------------------
-- Strata-aware partial regeneration
-------------------------------------------------------------------------------

-- |Regenerate a contiguous range of bars within an existing strata-aware
-- 'PC.ProgressionContext'. Mirrors 'runStrataGen' but seeded from the
-- source context's provenance instead of via 'Harmonic.Framework.Builder.Strata.initialPlacement', with a
-- one-step lookahead on the final regenerated bar so the @e → e+1@ seam
-- preserves walk-graph validity under 'Strata.allowedNext'.
--
-- By the Phase 1 invariant, any spliced sequence whose every edge satisfies
-- 'Harmonic.Framework.Builder.Strata.allowedNext' automatically produces only 'Harmonic.Rules.Types.Scale.ModeOk' bars. Maintaining
-- adjacency at both seams (the @s-1 → s@ seam is automatic via seeding;
-- the @e → e+1@ seam is the lookahead's job) is sufficient.
runStrataGenFrom :: PC.ProgressionContext
                 -> Int   -- ^ 1-indexed start of regen range (inclusive)
                 -> Int   -- ^ 1-indexed end of regen range (inclusive); wraps when @start > end@
                 -> GenConfig
                 -> IO (PC.ProgressionContext, GenerationDiagnostics)
runStrataGenFrom srcPC s _e gc = do
  let srcProvSeq = case PC.pcProvenance srcPC of
        Just sq -> sq
        Nothing -> error "runStrataGenFrom: source ProgressionContext lacks pcProvenance — call genFrom on a 'genI'/'genP'-derived context"
      srcProvList = toList srcProvSeq                -- [(Tristrata, StrataLabel)]
      srcN        = Seq.length srcProvSeq
      -- 1-indexed positions (wrap-aware).
      seedPos     = ((s - 2) `mod` srcN) + 1
      -- _gcLen carries the regen size: genFrom seeds it with the s..e
      -- range and the len modifier may expand it, exactly as on the
      -- legacy (FromProg) and jazz (FromProgJ) paths. The effective end
      -- bar and the seam target derive from it.
      rSize       = _gcLen gc
      effE        = ((s - 1 + rSize - 1) `mod` srcN) + 1
      targetPos   = (effE `mod` srcN) + 1
      (t_seed,   s_seed)   = srcProvList !! (seedPos   - 1)
      (t_target, s_target) = srcProvList !! (targetPos - 1)

      -- Cue: the source's triad-layer chord at seedPos. This was originally
      -- generated under the seed strata's narrowed context, so its absolute
      -- PCs lie within 's_seed's chroma — cue-validity is automatic.
      triadStates = toList (Prog.unProgression (PC.triadLayer srcPC))
      cueCS       = triadStates !! (seedPos - 1)

  rng <- createSystemRandom
  let basePctx = parseContextOnce (_gcTonal gc)
      allowed  = pcAllowedTristrata basePctx
      allowed' = if null allowed then Sc.validTristrata else allowed

      narrow :: Int -> [(Sc.StrataLabel, Sc.Tristrata)] -> [(Sc.StrataLabel, Sc.Tristrata)]
      narrow i pool =
        let pool1 = case _gcRelStrata gc of
              Just ps | not (null ps) ->
                let p = ps !! (i `mod` length ps)
                in [(s',t') | (s',t') <- pool, Sc.tristrataStrataAt t' p == s']
              _ -> pool
            pool2 = case _gcAbsStrata gc of
              Just ss | not (null ss) ->
                let lbl = ss !! (i `mod` length ss)
                in [(s',t') | (s',t') <- pool1, s' == lbl]
              _ -> pool1
        in pool2

  walkSeeds <- mapM (const (uniformRM (minBound :: Int, maxBound :: Int) rng))
                    [1 .. max 0 rSize]

  let -- Full (strata, tristrata) state space under the allow-list.
      allPairs = nub [ (Sc.tristrataStrataAt t p, t) | t <- allowed', p <- [1, 2, 3] ]

      -- Backward reachability to the seam target: @viableTbl !! i@ is the
      -- set of states permitted at regen bar @i@ from which the target
      -- bar's (strata, tristrata) is reachable through every remaining
      -- bar. Filtering each step's pool by it makes the e→e+1 seam an
      -- allowedNext edge BY CONSTRUCTION — there is no unfiltered escape
      -- hatch, so the module's walk-validity invariant holds on every
      -- output. A walk that cannot reconnect at all refuses loudly below.
      viableTbl :: [[(Sc.StrataLabel, Sc.Tristrata)]]
      viableTbl = [ viable i | i <- [0 .. rSize - 1] ]
        where
          viable i
            | i == rSize - 1 =
                [ p | p <- narrow i allPairs
                    , (s_target, t_target) `elem` Strata.allowedNext allowed' p ]
            | otherwise =
                let nxt = viableTbl !! (i + 1)
                in [ p | p <- narrow i allPairs
                       , any (`elem` nxt) (Strata.allowedNext allowed' p) ]

      -- Walk rSize bars seeded at (s_seed, t_seed), each pool restricted
      -- to target-reachable states. By induction the pool can only be
      -- empty at bar 0 (the cue cannot reach the target in rSize steps
      -- under the active narrowing) — the error names the way out.
      walkRange :: Int -> [Int] -> (Sc.StrataLabel, Sc.Tristrata) -> [(Sc.StrataLabel, Sc.Tristrata)]
      walkRange i seeds prev
        | i >= rSize = []
        | otherwise =
            let rawCands = narrow i (Strata.allowedNext allowed' prev)
                cands    = filter (`elem` (viableTbl !! i)) rawCands
                (seed, seedsRest) = case seeds of
                  (sd : rest) -> (sd, rest)
                  []          -> (0, [])
                chosen = case Strata.selectNextSeeded seed prev cands of
                  Just c  -> c
                  Nothing -> error
                    ("genFrom: the regenerated range cannot reconnect to the bar after it under the active strata constraints — widen the range (len), relax relStrata/absStrata, or regenerate through the seam")
            in chosen : walkRange (i + 1) seedsRest chosen

      -- Local barSeq passed to runStrataGenBody. Index 0 = seed (the cue),
      -- indices 1..rSize = the regenerated bars.
      regenBarSeq :: [(Sc.StrataLabel, Sc.Tristrata)]
      regenBarSeq = (s_seed, t_seed) : walkRange 0 walkSeeds (s_seed, t_seed)
      regenN      = length regenBarSeq   -- = rSize + 1

      strataOvertonesString :: Sc.StrataLabel -> String
      strataOvertonesString sl =
        unwords [ show (P.sharp (P.mkPitchClass (P.unPitchClass pc))) ++ "'"
                | pc <- Sc.strataChroma sl ]

      boostFor :: Int -> Double
      boostFor 0 = 1.0
      boostFor i =
        let (sCurr, tCurr) = regenBarSeq !! i
            (sPrev, tPrev) = regenBarSeq !! (i - 1)
            sGrand         = if i >= 2 then Just (fst (regenBarSeq !! (i - 2))) else Nothing
            mSame = if sCurr == sPrev then _gcBoostSame gc else 1.0
            mFlip = case sGrand of
                      Just sg | sCurr == sg && sCurr /= sPrev -> _gcBoostFlip gc
                      _                                        -> 1.0
            mTri  = if tCurr == tPrev then _gcBoostTri gc else 1.0
            _     = tPrev
        in mSame * mFlip * mTri

      pctxAt :: Int -> ParsedContext
      pctxAt barIdx1 =
        let i      = barIdx1
            (sl, _) = regenBarSeq !! i
            ctx'   = hcOvertones (strataOvertonesString sl) (_gcTonal gc)
            pctx   = parseContextOnce ctx'
            boost  = boostFor i
        in pctx { pcSoftBoost = boost, pcStrictContainment = True }

  -- Reuse runStrataGenBody for chain construction. Result has regenN bars
  -- across all layers: index 0 = the seed (cue) bar, indices 1..rSize =
  -- the regenerated bars.
  (regenPC, regenDiag) <- runStrataGenBody s_seed gc cueCS rng s_seed t_seed
                                           regenBarSeq pctxAt boostFor regenN

  let -- Drop the cue bar (index 0) from each layer and from provenance.
      dropCue :: Prog.Progression -> Prog.Progression
      dropCue (Prog.Progression sq) = Prog.Progression (Seq.drop 1 sq)

      insertPC = PC.ProgressionContext
        { PC.triadLayer   = dropCue (PC.triadLayer regenPC)
        , PC.strataLayer  = dropCue (PC.strataLayer regenPC)
        , PC.modeLayer    = dropCue (PC.modeLayer regenPC)
        , PC.pcProvenance = case PC.pcProvenance regenPC of
            Just sq -> Just (Seq.drop 1 sq)
            Nothing -> Nothing
        , PC.pcFamily     = PC.pcFamily regenPC
        }
      splicedPC = PC.pcSplice srcPC s effE insertPC

  pure (splicedPC, regenDiag)


-- |Report an invalid starting cue for 'Harmonic.Framework.Builder.genP'. Prints a warning naming
-- the cue's escape pitches alongside a grid of viable triads in the
-- starting strata. Returns silently — the caller emits an empty
-- 'Harmonic.Rules.Types.ProgressionContext.ProgressionContext' after this.
printInvalidCueError :: H.CadenceState -> Sc.StrataLabel -> IO ()
printInvalidCueError start s = do
  let rootPC       = P.unPitchClass (P.pitchClass (H.stateCadenceRoot start))
      intervals    = map P.unPitchClass (H.cadenceIntervals (H.stateCadence start))
      absPCs       = [ (i + rootPC) `mod` 12 | i <- intervals ]
      spelling     = H.inferSpelling absPCs
      enharm       = H.enharmonicFunc spelling
      chordName    = Prog.showHarmony enharm start
      strataPCs    = sort (map P.unPitchClass (Sc.strataChroma s))
      offenders    = [ p | p <- absPCs, p `notElem` strataPCs ]
      spellPC p    = show (enharm (P.mkPitchClass p))
      strataNames  = unwords (map spellPC strataPCs)
      offenderStr  = unwords (map spellPC offenders)
  putStrLn ""
  putStrLn $ "⚠ invalid starting state: " ++ chordName
             ++ "  (escapes strata " ++ show s
             ++ " — contains " ++ offenderStr ++ " outside {" ++ strataNames ++ "})"
  putStrLn $ "  viable triads in strata " ++ show s ++ " {" ++ strataNames ++ "}:"
  mapM_ (putStrLn . ("    " ++)) (viableTriadLines s enharm)
  putStrLn ""

-- |Produce one display line per root PC in the strata, listing every
-- distinct-by-name triad enumerated by 'possibleTriads' starting from
-- that root. Uses 'Prog.showTriad' for chord naming to match the grid
-- footer convention. Triads are padded to a uniform column width so
-- they align vertically across rows.
viableTriadLines :: Sc.StrataLabel -> (P.PitchClass -> P.NoteName) -> [String]
viableTriadLines s enharm =
  let strataPCs = sort (map P.unPitchClass (Sc.strataChroma s))
      triadsFor r =
        let ts = possibleTriads (r, strataPCs)
            names = nub [ Prog.showTriad enharm (H.toTriad enharm pcs) | pcs <- ts ]
        in names
      allNames  = concatMap triadsFor strataPCs
      colWidth  = if null allNames then 0 else maximum (map length allNames) + 2
      rootField = padR 4 . show . enharm . P.mkPitchClass
  in [ rootField r ++ "  " ++ concatMap (padR colWidth) (triadsFor r)
     | r <- strataPCs
     ]
  where
    padR n str = str ++ replicate (max 0 (n - length str)) ' '
